# fly.toml app configuration file generated for weird-cat-app on 2023-09-11T12:19:06+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weird-cat-app"
primary_region = "arn"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
